stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Djava.awt.headless=true"
  SPRING_PROFILES_ACTIVE: test

cache:
  paths:
    - .m2/repository

before_script:
  - echo "Running CI pipeline for YouQuiz project"

build:
  stage: build
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
  allow_failure: false

deploy:
  stage: deploy
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - echo "Starting deployment..."
    - mvn $MAVEN_CLI_OPTS spring-boot:run
  environment:
    name: production
    url: http://your-production-url
  only:
    - main

