version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: YouQuiz
    ports:
      - "5432:5432"
    networks:
      - app-network

  springboot-app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wrm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
